export default {
  app: './src/app',
  engine: './src/app/engine',
  objects: './src/app/objects',
  components: './src/app/components',
  config: './src/config',
  core: './src/app/core',
  utils: './src/app/utils',
  pages: './src/components/pages',
  public: './src/public',
  store: './src/app/store',
  styles: './src/app/styles',
  data: './src/data',
  assets: './src/assets',
};
